version: "3.8"

services: 
  app:
    image: node:14-alpine
    command: sh -c "yarn install && yarn run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"